#!/bin/sh

# bb-alts:
# installs Debian alternatives for busybox internal applets

# Copyright: (C) 2009-2019 Jordi Pujol <jordipujolp@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

_bb_targets() {
	echo "${bb}"
	dpkg -L bb-alts | grep -sxe '^/usr/bin/.*-busybox'
	echo "${USE_ALTS_FOREIGN:+"${BB_ALTS_FOREIGN:-}"}"  | \
		tr -s '[:space:]' '\n' | \
		cut -f 1 -d ','| cut -f 3 -s -d ':'
}

_deconfigure() {
	echo "Deconfiguring busybox alternatives." >&2
	/var/lib/dpkg/info/bb-alts.prerm deconfigure || :
}

_reconfigure() {
	echo "Reconfiguring busybox alternatives." >&2
	dpkg-reconfigure bb-alts || :
}

_list() {
	local a_name target alts \
		bb_targets="$(_bb_targets)"
	echo "Listing busybox alternatives." >&2
	for a_name in $(update-alternatives --get-selections | awk '{print $1}'); do
		for target in $(update-alternatives --list "${a_name}" 2> /dev/null | \
		grep -sxF "${bb_targets}"); do
			update-alternatives --query "${a_name}" 2>&1 | \
			awk -v target="${target}" 'NR <= 2 {print}
$1 == "Value:" {print}
$1 == "Alternative:" && $2 == target {p=1}
/^$/ && p == 1 {exit}
p == 1 {print}
END{print ""}'
		done
	done
	:
}

_list_active() {
	echo "Listing actually selected busybox alternatives." >&2
	update-alternatives --get-selections | \
		grep -swF "$(_bb_targets)" || :
}

_help() {
	echo "bb-alts
installs alternatives for busybox internal applets.
Options:
-d --deconfigure : removes all busybox alternatives.
-r --reconfigure : installs alternatives specified in /etc/bb-alts.conf
	detecting conflicts with other installed packages.
-l --list : lists all installed busybox alternatives.
	This is the default option.
-a --list-active : lists busybox alternatives that are actually selected.
-h --help : shows this text."
}

set -o errexit -o nounset -o noglob

bb="$(which "busybox")" || exit 1
. /etc/bb-alts.conf

test -n "${1:-}" || set -- "--list"

for option in "${@}"; do
	case "${option}" in
	-d|--deconfigure)
		_deconfigure;;
	-r|--reconfigure)
		_reconfigure;;
	-a|--list-active)
		_list_active;;
	-l|--list)
		_list;;
	-h|--help)
		_help;;
	*)
		echo "Invalid option: ${1}" >&2
		_help
		exit 1
		;;
	esac
done
