#!/bin/sh

# install busybox applets as utilities using Debian alternatives

# Copyright: (C) 2009-2016 Jordi Pujol <jordipujolp@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

_bb_targets() {
	printf '%s' "${bb}
$(dpkg -L bb-alts | grep -se '^/usr/bin/.*-busybox')" | \
tr -s '\n' '|'
}

_list() {
	local remove="${1}"
	local a_name bb_targets target
	local res
	bb_targets="$(_bb_targets)"
	[ -n "${remove}" ] || : > /var/tmp/bb-alts-reconfigure.txt
	for a_name in $(update-alternatives --get-selections | awk '{print $1}'); do
		for target in $(update-alternatives --list "${a_name}" 2> /dev/null | \
		grep -sxE "${bb_targets}"); do
			if [ -n "${remove}" ]; then
				echo "Removing alternative ${a_name} for ${target}" >&2
				res="$(update-alternatives --remove "${a_name}" "${target}" 2>&1)" || \
					printf 'Error: %s\n' "${res}" >&2
			else
				echo "Saving alternative ${a_name} for ${target}" >&2
				echo "${a_name}	${target}" >> /var/tmp/bb-alts-reconfigure.txt
			fi
		done
	done
	:
}

bb="$(which "busybox")" || exit 1

case "${1:-}" in
remove|deconfigure)
	echo "Removing all busybox alternatives." >&2
	_list "1" ;;
upgrade)
	echo "Saving list of busybox alternatives." >&2
	_list "" ;;
failed-upgrade)
	rm -f /var/tmp/bb-alts-reconfigure.txt ;;
esac

#DEBHELPER#
