#!/bin/sh

# install busybox applets as utilities using Debian alternatives

# Copyright: (C) 2009-2016 Jordi Pujol <jordipujolp@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

_remove_alternatives() {
	local a_name bb_targets target alts
	local res
	bb_targets="${bb}
$(dpkg -L bb-alts | grep -se '^/usr/bin/')"
	echo "Removing all busybox alternatives." >&2
	while read a_name; do
		[ -n "${a_name}" ] || continue
		alts="$(update-alternatives --list "${a_name}" 2> /dev/null)"
		while read target; do
			[ -n "${target}" ] || continue
			! echo "${alts}" | grep -qsxe "${target}" || \
				res="$(update-alternatives --remove "${a_name}" "${target}" 2>&1)" || \
					printf 'Error: %s\n' "${res}" >&2
		done << EOF
${bb_targets}
EOF
	done << EOF
$(update-alternatives --get-selections | awk '{print $1}')
EOF
	:
}

bb="$(which "busybox")" || exit 1

_remove_alternatives

#DEBHELPER#
