#!/bin/sh

# bb-alts:
# installs Debian alternatives for busybox internal applets

# Copyright: (C) 2009-2017 Jordi Pujol <jordipujolp@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

_comma_separated() {
	sed -re ':a
		N
		$!ba
		s/([^[:space:]])[[:space:]]+([^[:space:]])/\1'"${1:-","}"'\2/g
		s/[[:space:]]+//g'
}

_bb_targets() {
	local link_group alt
	( echo "${bb}"
	dpkg -L bb-alts | grep -se '^/usr/bin/.*-busybox'
	for link_group in ${USE_ALTS_FOREIGN:+${BB_ALTS_FOREIGN:-}}; do
		alt="$(echo "${link_group}" | cut -f 1 -d ',')"
		echo "${alt}" | cut -f 3 -s -d ':'
	done ) | \
	_comma_separated '|'
}

_check() {
	local a_name="${1}"
	test -L "/etc/alternatives/${a_name}" || return 0
	ls -L "/etc/alternatives/${a_name}" > /dev/null 2>&1 || \
		update-alternatives --auto "${a_name}"
}

_list() {
	local remove="${1}"
	local a_name target res
	local bb_targets="$(_bb_targets)"
	[ -n "${remove}" ] || : > /var/tmp/bb-alts-reconfigure.txt
	for a_name in $(update-alternatives --get-selections | awk '{print $1}'); do
		for target in $(update-alternatives --list "${a_name}" 2> /dev/null | \
		grep -sxE "${bb_targets}"); do
			if [ -n "${remove}" ]; then
				echo "Removing alternative ${a_name} for ${target}" >&2
				if res="$(update-alternatives --remove "${a_name}" "${target}" 2>&1)"; then
					_check "${a_name}"
				else
					printf 'Error: %s\n' "${res}" >&2
				fi
			else
				echo "Saving alternative ${a_name} for ${target}" >&2
				echo "${a_name}	${target}" >> /var/tmp/bb-alts-reconfigure.txt
			fi
		done
	done
}

bb="$(which "busybox")" || exit 1
. /etc/bb-alts.conf

case "${1:-}" in
remove|deconfigure)
	echo "Removing all busybox alternatives." >&2
	_list "1" ;;
upgrade)
	echo "Saving list of busybox alternatives." >&2
	_list "" ;;
failed-upgrade)
	rm -f /var/tmp/bb-alts-reconfigure.txt ;;
esac

#DEBHELPER#
